services:
  postgres:
    image: postgres
    container_name: library_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
#    networks:
#      - library-net

volumes:
  postgres_data: